import { FormEvent, useEffect, useMemo, useState } from "react";
import { ApiRequestError, createManagedUser, getManagedUsers, resetManagedUserPassword, updateManagedUser, type ManagedUser, type UserRole } from "./api.js";

const roles: UserRole[] = ["REQUESTER", "IT_STAFF", "ADMINISTRATOR"];
const roleLabel = (role: UserRole) => role === "IT_STAFF" ? "IT Staff" : role[0] + role.slice(1).toLowerCase();
const empty = { name: "", email: "", role: "REQUESTER" as UserRole, isActive: true, initialPassword: "" };

export default function UserManagement({ csrfToken }: { csrfToken: string }) {
  const [users, setUsers] = useState<ManagedUser[]>([]); const [search, setSearch] = useState(""); const [role, setRole] = useState<UserRole | "">("");
  const [create, setCreate] = useState(empty); const [editing, setEditing] = useState<ManagedUser | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { setError(""); try { setUsers(await getManagedUsers({ search, ...(role ? { role } : {}) })); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load users."); } }
  useEffect(() => { void load(); }, [role]);
  const selected = useMemo(() => users.find((u) => u.id === editing?.id) ?? editing, [users, editing]);
  async function submitCreate(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await createManagedUser(create, csrfToken); setCreate(empty); setMessage("User created. They must change the initial password on first sign-in."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create user."); } finally { setBusy(false); } }
  async function saveEdit(event: FormEvent) { event.preventDefault(); if (!editing) return; setBusy(true); setError(""); try { const updated = await updateManagedUser(editing.id, { name: editing.name, email: editing.email, role: editing.role, isActive: editing.isActive }, csrfToken); setEditing(updated); setMessage("User details saved."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save user."); } finally { setBusy(false); } }
  async function resetPassword() { if (!editing) return; const initialPassword = window.prompt("New initial password (8–128 characters)"); if (!initialPassword) return; setBusy(true); setError(""); try { await resetManagedUserPassword(editing.id, initialPassword, csrfToken); setMessage("Initial password reset. The user must change it after signing in."); await load(); } catch (e) { setError(e instanceof ApiRequestError ? e.message : "Unable to reset password."); } finally { setBusy(false); } }
  return <section className="user-management ticket-list-card" aria-labelledby="users-heading">
    <div className="staff-queue__heading"><div><p className="eyebrow mb-2">Administrator</p><h1 id="users-heading" className="h2 mb-1">User management</h1><p className="text-secondary mb-0">Create, update, activate, or deactivate accounts. Deletion is not available.</p></div></div>
    {error && <p className="state-panel state-panel--error" role="alert">{error}</p>}{message && <p className="staff-detail__message" role="status">{message}</p>}
    <form className="user-management__filters" onSubmit={(event) => { event.preventDefault(); void load(); }}><label>Search name or email<input className="form-control" value={search} onChange={(e) => setSearch(e.target.value)} /></label><label>Role<select className="form-select" value={role} onChange={(e) => setRole(e.target.value as UserRole | "")}><option value="">All roles</option>{roles.map((item) => <option key={item} value={item}>{roleLabel(item)}</option>)}</select></label><button className="btn btn-outline-zen align-self-end" type="submit">Search</button></form>
    <div className="user-management__table-wrap"><table className="table ticket-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th><span className="visually-hidden">Edit</span></th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td>{user.name}</td><td>{user.email}</td><td>{roleLabel(user.role)}</td><td><span className={user.isActive ? "status-badge" : "status-badge user-management__inactive"}>{user.isActive ? "Active" : "Inactive"}</span></td><td><button className="btn btn-sm btn-outline-zen" onClick={() => { setEditing(user); setMessage(""); }}>Edit</button></td></tr>)}</tbody></table></div>
    {!users.length && <p className="empty-state">No users match this search.</p>}
    <div className="user-management__forms"><form className="staff-detail__panel" onSubmit={submitCreate}><h2>Create user</h2><UserFields value={create} onChange={setCreate} password /><button className="btn btn-zen" disabled={busy}>{busy ? "Saving…" : "Create user"}</button></form>
    {selected && <form className="staff-detail__panel" onSubmit={saveEdit}><h2>Edit {selected.name}</h2><UserFields value={editing!} onChange={setEditing} /><div className="staff-detail__actions"><button className="btn btn-zen" disabled={busy}>{busy ? "Saving…" : "Save changes"}</button><button className="btn btn-outline-zen" type="button" disabled={busy} onClick={resetPassword}>Reset initial password</button><button className="btn btn-link" type="button" onClick={() => setEditing(null)}>Cancel</button></div></form>}</div>
  </section>;
}
function UserFields<T extends { name: string; email: string; role: UserRole; isActive: boolean; initialPassword?: string }>({ value, onChange, password = false }: { value: T; onChange: (value: T) => void; password?: boolean }) { const change = (next: Partial<T>) => onChange({ ...value, ...next }); return <><label>Name<input required maxLength={120} className="form-control" value={value.name} onChange={(e) => change({ name: e.target.value } as Partial<T>)} /></label><label>Email<input required type="email" className="form-control" value={value.email} onChange={(e) => change({ email: e.target.value } as Partial<T>)} /></label><label>Role<select className="form-select" value={value.role} onChange={(e) => change({ role: e.target.value as UserRole } as Partial<T>)}>{roles.map((item) => <option key={item} value={item}>{roleLabel(item)}</option>)}</select></label><label className="form-check"><input className="form-check-input" type="checkbox" checked={value.isActive} onChange={(e) => change({ isActive: e.target.checked } as Partial<T>)} /> <span className="form-check-label">Active account</span></label>{password && <label>Initial password<input required minLength={8} maxLength={128} type="password" className="form-control" value={value.initialPassword} onChange={(e) => change({ initialPassword: e.target.value } as Partial<T>)} /></label>}</>; }
